AwesomeBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home, post, category, FilterByTag, authorView, SearchResultsView

app_name = "blog"

urlpatterns = [
    path('', home, name='home'),
    path('blog/<slug:url>',post),
    path('category/<slug:url>',category),
    path('tag/<slug:tag>/', FilterByTag, name='tag'),
    path('<str:username>/<str:author_id>', authorView),
    path('search/', SearchResultsView, name='search_results'),
]

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import AboutPageView, ContactPageView, PrivacyPageView

app_name = "pages"

urlpatterns = [
    path('about', AboutPageView, name='about'),
    path('contact', ContactPageView, name='contact'),
    path('privacy', PrivacyPageView, name='privacy'),
]

templates/author.html
{%extends 'base.html'%}

{%block title%} welcome title {%endblock%}

{%block content%}

<main class="main-wrap">
    <section class="m-hero no-picture aos-init aos-animate" data-aos="fade">
        <div class="m-hero__content aos-init aos-animate" data-aos="fade-down">
            <div class="m-hero-avatar"
                style="background-image: url('{{ currentUser.profile.user_image.url }}');"></div>
            <h1 class="m-hero-title">{{currentUser.first_name}} {{currentUser.last_name}}</h1>
            <p class="m-hero-description">{{profile.user_bio}}</p>
            <div class="m-hero__meta">
                <ul class="m-hero-social">
                    <li>
                        <a href="{{ currentUser.profile.author_url }}" target="_blank">
                            <span class="icon-globe"></span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ currentUser.profile.author_fcebook_link }}" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                </ul>
                <ul class="m-hero-stats">
                    <li>{{num_post}} Posts</li>
                    <li>•</li>
                    <li>{{ currentUser.profile.location }}</li>
                </ul>
            </div>
        </div>
    </section>

    <div class="l-content">
        <div class="l-wrapper aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
            <div class="l-grid centered">
                {% for post in author_post %}
                <article class="m-article-card  post tag-tips-tricks tag-psychology tag-models">
                    <div class="m-article-card__picture">
                        <a href="/blog/{{post.post_url}}" class="m-article-card__picture-link"
                            aria-hidden="true" tabindex="-1"></a>
                        <img class="m-article-card__picture-background"
                            src="/media/{{post.post_image}}" alt="{{post.post_title}}">
                        <a href="/{{post.post_user}}/{{post.post_user.id}}" class="m-article-card__author js-tooltip"
                            aria-label="Adam" data-tippy-content="Posted by Adam ">
                            <div style="background-image: url('{{ post.post_user.profile.user_image.url }}');"></div>
                        </a>
                    </div>
                    <div class="m-article-card__info">
                        <a href="/category/{{post.post_in_cat.cat_url}}" class="m-article-card__tag">{{post.post_in_cat}}</a>
                        <a href="/blog/{{post.post_url}}" class="m-article-card__info-link"
                            aria-label="{{post.post_title}}">
                            <div>
                                <h2 class="m-article-card__title js-article-card-title " title="{{post.post_title}}">
                                    {{post.post_title}}
                                </h2>
                            </div>
                            <div class="m-article-card__timestamp">
                                <span>{{ post.whenpublished }}</span>
                                <span>•</span>
                                <span>{{post.get_readtime}} read</span>
                            </div>
                        </a>
                    </div>
                </article>
                {% endfor %}
            </div>
            {%include 'pagination.html' with page=author_post %}
        </div>
    </div>
</main>

{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} {%endblock%}</title>

    {%load static%}

    <link rel="shortcut icon" href="/media/{{siteDetail.favicon}}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/app.css'%}">
    <link rel="stylesheet" href="{% static 'css/listing.css'%}">
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
    <link rel="stylesheet" href="{% static 'css/post.css'%}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css'%}">
</head>

<body>
    {%include 'header.html' %}

    {%block content%}

    {%endblock%}
    {%include 'footer.html' %}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/app.js'%}"></script>
    <script src="{% static 'js/content-api.min.js'%}"></script>
    <script src="{% static 'js/home.js'%}"></script>
    <script src="{% static 'js/manifest.js'%}"></script>
    <script src="{% static 'js/polyfill.min.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
    <script src="{% static 'js/vendor.js'%}"></script>
</body>

</html>

templates/category.html
{%extends 'base.html'%}

{%block title%} welcome title {%endblock%}

{%block content%}

<main class="main-wrap">
  <section class="m-hero no-picture aos-init aos-animate" data-aos="fade">
    <div class="m-hero__content aos-init aos-animate" data-aos="fade-down">
      <h1 class="m-hero-title bigger">{{cat.cat_title}}</h1>
      <div class="m-hero__meta">
        <ul class="m-hero-stats">
          <li>
            {{ num_post }} posts with this category </li>
        </ul>
      </div>
    </div>
  </section>
  <article>
    <div class="l-content">
      <div class="l-wrapper in-post aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
        <div class="l-post-content">
          <div class="pos-relative js-post-content">
            {%for post in posts%}
            <figure class="kg-card kg-bookmark-card"><a class="kg-bookmark-container"
                href="/blog/{{post.post_url}}">
                <div class="kg-bookmark-content">
                  <div class="kg-bookmark-title">{{post.post_title}}</div>
                  <div class="kg-bookmark-description">{{post.post_content |truncatewords:25| safe}}</div>
                  <div class="kg-bookmark-metadata"><img class="kg-bookmark-icon"
                      src="/media/{{siteDetail.favicon}}" alt="Favicon"><span
                      class="kg-bookmark-author">{{siteDetail.site_name}}</span>
                      <span class="kg-bookmark-publisher">{{post.post_user}}</span></div>
                </div>
                <div class="kg-bookmark-thumbnail">
                  <img src="/media/{{post.post_image}}" alt="{{post.post_title}}"/> 
                </div>
              </a>
            </figure>
            {%endfor%}
          </div>

          {%include 'pagination.html' with page=posts %}
          
        </div>
      </div>
    </div>
  </article>
</main>

{%endblock%}

templates/footer.html
<footer class="m-footer">
  <div class="m-footer__content">
    <nav class="m-footer__nav-secondary" role="navigation" aria-label="Secondary menu in footer">

      <ul class="m-secondary-menu">
        <li>
          <a href="{% url 'pages:about' %}">About Us</a>
        </li>
        <li>
          <a href="{% url 'pages:contact' %}">Contact Us</a>
        </li>
        <li>
          <a href="{% url 'pages:privacy' %}">privacy Policy</a>
        </li>
      </ul>

    </nav>
    <nav class="m-footer-social">
      <a href="{{socialLink.twitter_link}}" target="_blank" rel="noopener" aria-label="Twitter">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="{{socialLink.fcebook_link}}" aria-label="RSS">
        <i class="fab fa-facebook-f"></i>
      </a>
    </nav>
    <p class="m-footer-copyright">
      <span>{{siteDetail.site_name}} © <script>
          document.write(new Date().getFullYear())
        </script></span>
      <span>&nbsp; • &nbsp;</span>
      <span>{{siteDetail.site_description}}</span>
    </p>

  </div>
</footer>

templates/header.html
<header class="m-header with-picture js-header headroom headroom--not-bottom headroom--pinned headroom--top">
  <div class="m-mobile-topbar aos-init aos-animate" data-aos="fade-down">
    <button class="m-icon-button in-mobile-topbar js-open-menu" aria-label="Open menu">
      <span class="icon-menu" aria-hidden="true"></span>
    </button>
    <a href="{% url 'blog:home'%}" class="m-logo in-mobile-topbar">
      <img src="/media/{{siteDetail.site_logo}}" alt="{{siteDetail.site_name}}">
    </a>
    <button class="m-icon-button in-mobile-topbar js-open-search" aria-label="Open search">
      <span class="icon-search" aria-hidden="true"></span>
    </button>
  </div>


  <div class="m-menu js-menu">
    <button class="m-icon-button outlined as-close-menu js-close-menu" aria-label="Close menu">
      <span class="icon-close"></span>
    </button>
    <div class="m-menu__main aos-init aos-animate" data-aos="fade-down">
      <div class="l-wrapper">
        <div class="m-nav js-main-nav toggle-overflow">
          <nav class="m-nav__left js-main-nav-left toggle-overflow" role="navigation" aria-label="Main menu">
            <ul>
              <li class="only-desktop">
                <a href="{% url 'blog:home'%}" class="m-logo">
                  <img src="/media/{{siteDetail.site_logo}}" alt="{{siteDetail.site_name}}">
                </a>
              </li>
              {%for menu in menuItem%}
              <li><a href="/category/{{menu.menu_item.cat_url}}">{{menu.menu_item.cat_title}}</a></li>
              {%endfor%}
              <li class="more">
                <span>
                  <a href="javascript:void(0);" class="js-open-secondary-menu" aria-expanded="false">
                    More
                    <span class="icon-chevron-down" aria-hidden="true"></span>
                  </a>
                </span>
              </li>
              <li class="submenu-option js-submenu-option">
                <button class="m-icon-button in-menu-main more js-toggle-submenu" aria-label="Open submenu">
                  <span class="icon-more" aria-hidden="true"></span>
                </button>
                <div class="m-submenu js-submenu closed">
                  <div class="l-wrapper in-submenu">
                    <section class="m-recent-articles">
                      <h3 class="m-submenu-title in-recent-articles">Recent articles</h3>
                      <div class="glide js-recent-slider glide--ltr glide--slider glide--swipeable">
                        <div class="glide__track" data-glide-el="track">
                          <div class="glide__slides">

                            {%for p in header_post%}
                            <div class="glide__slide">
                              <a href="/blog/sex-and-health-myths-and-facts/" class="m-recent-article">
                                <div class="m-recent-article__picture ">
                                  <img src="/media/{{p.post_image}}" loading="lazy" alt="{{p.post_title}}">
                                </div>
                                <h3 class="m-recent-article__title js-recent-article-title"
                                  title="Sex and health: myths and facts">{{p.post_title}}</h3>
                                <span class="m-recent-article__date">20 hours ago</span>
                              </a>
                            </div>
                            {% endfor%}
                          </div>
                        </div>
                      </div>
                    </section>
                    <section class="m-tags">
                      <h3 class="m-submenu-title">Tags</h3>
                      <ul>
                        {%for tag in tags%}
                        <li><a href="{% url 'blog:tag' tag %}">{{tag}}</a></li>
                        {%endfor%}
                      </ul>
                    </section>
                  </div>
                </div>
              </li>
            </ul>
          </nav>
          <div class="m-nav__right">
            <a href="{{socialLink.youtube_link}}" target="_blank"
              style="border-radius:24px;padding:6px 15px;color:#ffffff;background:#af262f;">Visit Youtube</a>



            <div class="search-box">
              <form action="{% url 'blog:search_results' %}" method="get">
                <input class="search-input" type="text" required name="q" placeholder="Pesquise">
                <button id="search_btn" class="m-icon-button in-menu-main" aria-label="Open search">
                  <span class="icon-search" aria-hidden="true"></span>
                </button>
              </form>
            </div>

            <div class="m-toggle-darkmode js-tooltip" data-tippy-content="Toggle dark mode" tabindex="0">
              <label for="toggle-darkmode" class="sr-only">
                Toggle dark mode
              </label>
              <input id="toggle-darkmode" type="checkbox" class="js-toggle-darkmode">
              <div>
                <span class="icon-moon moon" aria-hidden="true"></span>
                <span class="icon-sunny sun" aria-hidden="true"></span>
              </div>

            </div>



          </div>

        </div>


      </div>
    </div>
  </div>






  <div id="secondary-navigation-template" style="display: none;">

    <ul class="m-secondary-menu">
      {%for dropmenu in headerDropdownMenu%}
      <li><a
          href="/category/{{dropmenu.header_drop_menu_item.cat_url}}">{{dropmenu.header_drop_menu_item.cat_title}}</a>
      </li>
      {%endfor%}
    </ul>

  </div>

</header>

templates/home.html
{%extends 'base.html'%}

{%block title%} {{siteDetail.site_name}} {%endblock%}

{%block content%}


<main class="main-wrap">
    <div class="l-content">
        <div class="l-wrapper aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
            <div class="l-grid centered">
                <div class="m-featured-slider glide js-featured-slider glide--ltr glide--slider glide--swipeable">
                    <div class="glide__track" data-glide-el="track">
                        <div class="m-featured-slider__list glide__slides">
                            {%for p in latest_post%}
                            <div class="m-featured-slider__list__item glide__slide js-featured-slide"
                                style="width: 787px; margin-left: 0px;">
                                <article class="m-featured-article ">
                                    <div class="m-featured-article__picture">
                                        <div style="background-image: url(/media/{{p.post_image}});"
                                            id="featured-bg-607fe83214ce8c0001027539"></div>
                                    </div>
                                    <div class="m-featured-article__meta">
                                        <a href="{{p.post_user}}/{{p.post_user.id}}"
                                            class="m-featured-article__author js-tooltip" aria-label="{{p.post_user}}"
                                            data-tippy-content="Posted by {{p.post_user}} ">
                                            <div style="background-image: url('{{ p.post_user.profile.user_image.url }}');">
                                            </div>
                                        </a>
                                        <a href="/category/{{p.post_in_cat.cat_url}}"
                                            class="m-featured-article__tag">{{p.post_in_cat}}</a>
                                    </div>
                                    <div class="m-featured-article__ribbon">
                                        <span class="icon-star"></span>
                                        <span>Featured</span>
                                    </div>
                                    <a href="/blog/{{p.post_url}}"
                                        class="m-featured-article__content">
                                        <h2 class="m-featured-article__title js-featured-article-title"
                                            title="{{p.post_title}}">
                                            {{p.post_title}} </h2>
                                        <div class="m-featured-article__timestamp">
                                            <span>{{ p.whenpublished }}</span>
                                            <span>•</span>
                                            <span>{{p.get_readtime}} read</span>
                                        </div>
                                    </a>
                                </article>
                            </div>
                            {%endfor%}
                            
                        </div>
                    </div>
                    <div data-glide-el="controls" class="glide__arrows js-featured-slider-controls">
                        <button data-glide-dir="<"
                            class="m-icon-button in-featured-articles glide-prev js-featured-slider-previous"
                            aria-label="Previous" disabled="">
                            <span class="icon-arrow-left" aria-hidden="true"></span>
                        </button>
                        <button data-glide-dir=">"
                            class="m-icon-button in-featured-articles glide-next js-featured-slider-next"
                            aria-label="Next">
                            <span class="icon-arrow-right" aria-hidden="true"></span>
                        </button>
                    </div>
                </div>

                {%for p in posts%}
                <article class="m-article-card  post tag-psychology featured">
                    <div class="m-article-card__picture">
                        <a href="/blog/{{p.post_url}}"
                            class="m-article-card__picture-link" aria-hidden="true" tabindex="-1"></a>
                        <img width="500" height="280" src="/media/{{p.post_image}}"
                            class="m-article-card__picture-background wp-post-image" alt="" loading="lazy"
                            srcset="/media/{{p.post_image}} 500w, /media/{{p.post_image}} 300w"
                            sizes="(max-width: 500px) 100vw, 500px"> <a href="{{p.post_user}}/{{p.post_user.id}}"
                            class="m-article-card__author js-tooltip" aria-label="{{p.post_user}}"
                            data-tippy-content="Posted by {{p.post_user}} ">
                            <div style="background-image: url('{{ p.post_user.profile.user_image.url }}');">
                            </div>
                        </a>
                        <a href="/blog/{{p.post_url}}"
                            class="m-article-card__featured js-tooltip" data-tippy-content="Featured"
                            aria-label="Featured">
                            <span class="icon-star" aria-hidden="true"></span>
                        </a>
                    </div>
                    <div class="m-article-card__info">
                        <a href="/category/{{p.post_in_cat.cat_url}}" class="m-article-card__tag">{{p.post_in_cat}}</a>
                        <a href="/blog/{{p.post_url}}" class="m-article-card__info-link" aria-label="{{p.post_title}}">
                            <div>
                                <h2 class="m-article-card__title js-article-card-title " title="{{p.post_title}}">
                                    {{p.post_title}} </h2>
                            </div>
                            <div class="m-article-card__timestamp">
                                <span>{{ p.whenpublished }}</span>
                                <span>•</span>
                                <span>{{p.get_readtime}} read</span>
                            </div>
                        </a>
                    </div>
                </article>
                {%endfor%}
            </div>
            {%include 'pagination.html' with page=posts %}
        </div>
    </div>
</main>

{%endblock%}

templates/pagination.html
<div class="l-wrapper">
    <div class="m-pagination">
        <div class="pagination_inner" style="display: flex; align-items: center;">
            {% if page.has_previous%}
            <a class="m-icon-button filled in-pagination-left" href="?page={{page.previous_page_number}}">
                <span class="icon-arrow-left"></span>
            </a>
            {% endif %}
            <div style="margin:0 10px;" class="page_range">Page {{page.number}} Of {{page.paginator.num_pages}}</div>
            {% if page.has_next%}
            <a class="m-icon-button filled in-pagination-right" href="?page={{page.next_page_number}}">
                <span class="icon-arrow-right"></span>
            </a>
            {% endif %}
        </div>
    </div>
</div>

templates/posts.html
{%extends 'base.html'%}

{%block title%} {{post.post_title}} {%endblock%}

{%block content%}
<main class="main-wrap">
  <article>
    <div class="l-content in-post">
      <div class="l-wrapper in-post js-aos-wrapper aos-init aos-animate">
        <div class="l-post-content js-progress-content">
          <header class="m-heading">
            <h1 class="m-heading__title in-post">{{post.post_title}}</h1>
            <div class="m-heading__meta">
              <a href="/category/{{cat.cat_url}}"
                class="m-heading__meta__tag">{{cat.cat_title}}</a>
              <span class="m-heading__meta__divider" aria-hidden="true">•</span>
              <span class="m-heading__meta__time">{{ post.whenpublished }}</span>
            </div>
          </header>
          <div class="pos-relative js-post-content">
            <div class="m-share">
              <div class="m-share__content js-sticky">
                <a class="m-icon-button filled in-share"
                  href="whatsapp://send?text=%E0%A6%AE%E0%A6%BF%E0%A7%9F%E0%A6%BE%E0%A6%A8%E0%A6%AE%E0%A6%BE%E0%A6%B0%E0%A7%87%E0%A6%B0+%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%AC%E0%A6%BE%E0%A6%9A%E0%A6%A8+%E0%A6%95%E0%A7%8B%E0%A6%A8%E0%A7%8B+%E0%A6%86%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BE%E0%A6%B0+%E0%A6%9C%E0%A6%BE%E0%A7%9F%E0%A6%97%E0%A6%BE+%E0%A6%A4%E0%A7%88%E0%A6%B0%E0%A6%BF+%E0%A6%95%E0%A6%B0%E0%A7%87+%E0%A6%A8%E0%A6%BE http%3A%2F%2Fblog.decktheme.ml%2F%25e0%25a6%25ae%25e0%25a6%25bf%25e0%25a7%259f%25e0%25a6%25be%25e0%25a6%25a8%25e0%25a6%25ae%25e0%25a6%25be%25e0%25a6%25b0%25e0%25a7%2587%25e0%25a6%25b0-%25e0%25a6%25a8%25e0%25a6%25bf%25e0%25a6%25b0%25e0%25a7%258d%25e0%25a6%25ac%25e0%25a6%25be%25e0%25a6%259a%25e0%25a6%25a8-%25e0%25a6%2595%25e0%25a7%258b%25e0%25a6%25a8%25e0%25a7%258b%2F"
                  target="_blank">
                  <i class="fab fa-whatsapp"></i>
                </a>

                <a class="m-icon-button filled in-share"
                  href="https://twitter.com/intent/tweet?text=%E0%A6%AE%E0%A6%BF%E0%A7%9F%E0%A6%BE%E0%A6%A8%E0%A6%AE%E0%A6%BE%E0%A6%B0%E0%A7%87%E0%A6%B0+%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%AC%E0%A6%BE%E0%A6%9A%E0%A6%A8+%E0%A6%95%E0%A7%8B%E0%A6%A8%E0%A7%8B+%E0%A6%86%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BE%E0%A6%B0+%E0%A6%9C%E0%A6%BE%E0%A7%9F%E0%A6%97%E0%A6%BE+%E0%A6%A4%E0%A7%88%E0%A6%B0%E0%A6%BF+%E0%A6%95%E0%A6%B0%E0%A7%87+%E0%A6%A8%E0%A6%BE&amp;url=http%3A%2F%2Fblog.decktheme.ml%2F%25e0%25a6%25ae%25e0%25a6%25bf%25e0%25a7%259f%25e0%25a6%25be%25e0%25a6%25a8%25e0%25a6%25ae%25e0%25a6%25be%25e0%25a6%25b0%25e0%25a7%2587%25e0%25a6%25b0-%25e0%25a6%25a8%25e0%25a6%25bf%25e0%25a6%25b0%25e0%25a7%258d%25e0%25a6%25ac%25e0%25a6%25be%25e0%25a6%259a%25e0%25a6%25a8-%25e0%25a6%2595%25e0%25a7%258b%25e0%25a6%25a8%25e0%25a7%258b%2F&amp;"
                  rel="noopener" target="_blank">
                  <i class="fab fa-twitter"></i>
                </a>

                <a class="m-icon-button filled in-share"
                  href="https://www.facebook.com/sharer/sharer.php?u=/blog/{{post.post_url}}"
                  rel="noopener" target="_blank">
                  <i class="fab fa-facebook-f"></i>
                </a>


                <button class="m-icon-button filled in-share progress js-scrolltop" aria-label="Scroll to top">
                  <span class="icon-arrow-top" aria-hidden="true"></span>
                  <svg aria-hidden="true" viewBox="0 0 50 50" style="opacity: 1;">
                    <circle class="progress-ring__circle js-progress" fill="transparent" r="23" stroke-width="3" cx="25"
                      cy="25" style="stroke-dasharray: 157.08, 157.08; stroke-dashoffset: 157.08;"></circle>
                  </svg>
                </button>
              </div>
            </div>
            <figure class="kg-card kg-image-card kg-width-wide">
              <img src="/media/{{post.post_image}}" alt="{{post.post_title}}"></figure>
            <p>
              {{post.post_content|safe}}
            </p>
            <section class="m-tags in-post">
            </section>
          </div>
        </div>
      </div>

      <section class="m-author">
        <div class="m-author__content">
          <div class="m-author__picture">
            <a href="/{{post.post_user}}/{{post.post_user.id}}" class="m-author-picture" aria-label="admin">
              <div style="background-image: url('{{ post.post_user.profile.user_image.url }}');"></div>
            </a>
          </div>
          <div class="m-author__info">
            <h4 class="m-author__name">
              <a href="/{{post.post_user}}/{{post.post_user.id}}">{{post.post_user}}</a>
            </h4>
            <p class="m-author__bio">{{ post.post_user.profile.user_bio }}</p>
            <ul class="m-author-links">
              <li>
                <a href="{{ post.post_user.profile.author_url }}" target="_blank">
                  <span class="icon-globe" aria-hidden="true"></span>
                </a>
              </li>
              <li>
                <a href="{{ post.post_user.profile.author_fcebook_link }}" target="_blank">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
      <section class="m-recommended">
        <div class="l-wrapper in-recommended">
          <h3 class="m-section-title in-recommended">Recommended for you</h3>
          <div class="m-recommended-articles">
            <div class="m-recommended-slider glide js-recommended-slider glide--swipeable glide--ltr glide--slider">
              <div class="glide__track" data-glide-el="track">
                <div class="glide__slides"
                  style="transition: transform 0ms cubic-bezier(0.165, 0.84, 0.44, 1) 0s; width: 423.667px; transform: translate3d(0px, 0px, 0px);">
                  {% for post in related_posts %}
                  <div class="m-recommended-slider__item glide__slide glide__slide--active" style="width: 423.667px;">
                    <article
                      class="m-article-card  post tag-masturbation tag-psychology tag-sex tag-sexuality-education tag-tricks">
                      <div class="m-article-card__picture">
                        <a href="/blog/{{post.post_url}}"
                          class="m-article-card__picture-link" aria-hidden="true" tabindex="-1"></a>
                        <img width="497" height="280" src="/media/{{post.post_image}}"
                          class="m-article-card__picture-background wp-post-image" alt="" loading="lazy"
                          srcset="/media/{{post.post_image}} 728w, /media/{{post.post_image}} 300w"
                          sizes="(max-width: 497px) 100vw, 497px"> <a href="{{post.post_user}}/{{post.post_user.id}}"
                          class="m-article-card__author js-tooltip" aria-label="admin"
                          data-tippy-content="Posted by admin ">
                          <div style="background-image: url('{{ post.post_user.profile.user_image.url }}');">
                          </div>
                        </a>
                      </div>
                      <div class="m-article-card__info">
                        <a href="/category/{{post.post_in_cat.cat_url}}" class="m-article-card__tag">{{post.post_in_cat}}</a>
                        <a href="/blog/{{post.post_url}}"
                          class="m-article-card__info-link"
                          aria-label="{{ post.post_title }}">
                          <div>
                            <h2 class="m-article-card__title js-article-card-title"
                              title="{{ post.post_title }}">
                              {{ post.post_title }} </h2>
                          </div>
                          <div class="m-article-card__timestamp">
                            <span>{{ post.whenpublished }}</span>
                            <span>•</span>
                            <span>{{post.get_readtime}}</span>
                          </div>
                        </a>
                      </div>
                    </article>
                  </div>
                  {% endfor %}
                </div>
              </div>

            </div>
          </div>
        </div>
      </section>
    </div>
  </article>
</main>
{%load static%}
<script src="{% static 'js/post.js'%}"></script>
{%endblock%}